spring:
  kafka:
    bootstrap-servers: localhost:9092
    properties:
      schema.registry.url: ${SCHEMA_REGISTRY_URL:http://localhost:8081}
app:
  topic:
    
    #SENDER (CREATION CONTEXT)
    event-driven-topic-in: loyalty.internal.last.update.identifier.context.identification
    
    #RECEIVER (CONTEXT
    event-driven-topic-out: loyalty.internal.last.out.identifier.context.identification
    
    event-driven-topic-error: lys.identification.error
    

logging:
  level:
    root: info
    org.springframework.web: ERROR
    com.adeo.event.driven.sample: DEBUG