spring:
  kafka:
    bootstrap-servers: localhost:9092
    properties:
      schema.registry.url: ${SCHEMA_REGISTRY_URL:http://localhost:8081}
app:
  topic:
    event-driven-topic-in: context-driven-in
    event-driven-topic-out: context-driven-out
    event-driven-topic-error: context-driven-error
    

logging:
  level:
    root: info
    org.springframework.web: ERROR
    com.adeo.event.driven.sample: DEBUG